---
grails:
  profile: web
  codegen:
    defaultPackage: mailsenderquartz
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@MailSenderQurtz@'
    version: '@v1.0@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
endpoints:
  jmx:
    unique-names: true

---
hibernate:
  hbm2ddl:
    auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prod_accesos?autoReconnect=true&useSSL=false
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: "root"
    properties:
      jmxEnabled: true
      initialSize: 5
      maxActive: 50
      minIdle: 5
      maxIdle: 25
      maxWait: 10000
      maxAge: 600000
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1
      validationQueryTimeout: 3
      validationInterval: 15000
      testOnBorrow: true
      testWhileIdle: true
      testOnReturn: false
      jdbcInterceptors: ConnectionState
      defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

environments:
  development:
    dataSource:
      dbCreate: none
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/prod_accesos?autoReconnect=true&useSSL=false
      username: root
      password: "root"
  test:
    dataSource:
      dbCreate: none
      url: jdbc:mysql://localhost:3306/prod_accesos?autoReconnect=true&useSSL=false
  production:
    dataSource:
      dbCreate: none
      url: jdbc:mysql://localhost:3306/prod_accesos?autoReconnect=true&useSSL=false
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
environments:
  development:
    quartz:
      autoStartup: true
  test:
    quartz:
      autoStartup: false
  production:
    quartz:
      autoStartup: true
---
grails:
  mail:
    host: "smtp.gmail.com"
    port: 465
    username: "user@mail"
    password: "password"
    props:
      mail.smtp.auth: "true"
      mail.smtp.socketFactory.port: "465"
      mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
      mail.smtp.socketFactory.fallback: "false"
---
server:
  contextPath: '/MailSenderQuartz'

